--
-- PostgreSQL database dump
--

\restrict hyR4KezQV0VrSlIls5NQfHoWqzRbeUdvyhpDxKsk7gEn7WopyM4MCbKlEBJuGmZ

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: tasks_actionnetworkconfig; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tasks_actionnetworkconfig (
    id bigint NOT NULL,
    api_key text NOT NULL,
    webhook_url character varying(255) NOT NULL,
    webhook_secret character varying(255) NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.tasks_actionnetworkconfig OWNER TO postgres;

--
-- Name: tasks_actionnetworkconfig_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tasks_actionnetworkconfig ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tasks_actionnetworkconfig_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tasks_assignmentrule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tasks_assignmentrule (
    id bigint NOT NULL,
    keyword character varying(100) NOT NULL,
    is_active boolean NOT NULL,
    team_id bigint NOT NULL
);


ALTER TABLE public.tasks_assignmentrule OWNER TO postgres;

--
-- Name: tasks_assignmentrule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tasks_assignmentrule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tasks_assignmentrule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tasks_clickupconfig; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tasks_clickupconfig (
    id bigint NOT NULL,
    api_token text NOT NULL,
    workspace_id character varying(255) NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.tasks_clickupconfig OWNER TO postgres;

--
-- Name: tasks_clickupconfig_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tasks_clickupconfig ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tasks_clickupconfig_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tasks_databaseconfig; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tasks_databaseconfig (
    id bigint NOT NULL,
    engine character varying(20) NOT NULL,
    name character varying(255) NOT NULL,
    "user" character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    host character varying(255) NOT NULL,
    port character varying(10) NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.tasks_databaseconfig OWNER TO postgres;

--
-- Name: tasks_databaseconfig_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tasks_databaseconfig ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tasks_databaseconfig_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tasks_emailconfig; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tasks_emailconfig (
    id bigint NOT NULL,
    provider character varying(20) NOT NULL,
    host character varying(255) NOT NULL,
    port integer NOT NULL,
    username character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    use_tls boolean NOT NULL,
    use_ssl boolean NOT NULL,
    from_email character varying(254) NOT NULL,
    from_name character varying(100) NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT tasks_emailconfig_port_check CHECK ((port >= 0))
);


ALTER TABLE public.tasks_emailconfig OWNER TO postgres;

--
-- Name: tasks_emailconfig_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tasks_emailconfig ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tasks_emailconfig_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tasks_n8nconfig; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tasks_n8nconfig (
    id bigint NOT NULL,
    base_url character varying(255) NOT NULL,
    api_key text NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.tasks_n8nconfig OWNER TO postgres;

--
-- Name: tasks_n8nconfig_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tasks_n8nconfig ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tasks_n8nconfig_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tasks_redisconfig; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tasks_redisconfig (
    id bigint NOT NULL,
    url character varying(255) NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.tasks_redisconfig OWNER TO postgres;

--
-- Name: tasks_redisconfig_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tasks_redisconfig ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tasks_redisconfig_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tasks_task; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tasks_task (
    id bigint NOT NULL,
    job_id character varying(50) NOT NULL,
    email_from character varying(254) NOT NULL,
    email_subject text NOT NULL,
    task_type character varying(100) NOT NULL,
    task_detail text NOT NULL,
    priority character varying(20) NOT NULL,
    note text,
    status character varying(30) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    closed_at timestamp with time zone,
    assign_to_id bigint,
    external_id character varying(255) NOT NULL,
    source character varying(20) NOT NULL
);


ALTER TABLE public.tasks_task OWNER TO postgres;

--
-- Name: tasks_task_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tasks_task ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tasks_task_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tasks_taskattachment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tasks_taskattachment (
    id bigint NOT NULL,
    file character varying(100) NOT NULL,
    filename character varying(255) NOT NULL,
    content_type character varying(100) NOT NULL,
    uploaded_at timestamp with time zone NOT NULL,
    task_id bigint NOT NULL,
    uploaded_by_id integer
);


ALTER TABLE public.tasks_taskattachment OWNER TO postgres;

--
-- Name: tasks_taskattachment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tasks_taskattachment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tasks_taskattachment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tasks_tasksync; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tasks_tasksync (
    id bigint NOT NULL,
    source character varying(20) NOT NULL,
    external_id character varying(255) NOT NULL,
    raw jsonb NOT NULL,
    synced_at timestamp with time zone NOT NULL,
    task_id bigint NOT NULL
);


ALTER TABLE public.tasks_tasksync OWNER TO postgres;

--
-- Name: tasks_tasksync_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tasks_tasksync ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tasks_tasksync_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tasks_team; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tasks_team (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    email character varying(254) NOT NULL,
    is_active boolean NOT NULL
);


ALTER TABLE public.tasks_team OWNER TO postgres;

--
-- Name: tasks_team_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tasks_team ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tasks_team_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tasks_telegramconfig; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tasks_telegramconfig (
    id bigint NOT NULL,
    bot_token text NOT NULL,
    chat_id character varying(255) NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.tasks_telegramconfig OWNER TO postgres;

--
-- Name: tasks_telegramconfig_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tasks_telegramconfig ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tasks_telegramconfig_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tasks_whatsappconfig; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tasks_whatsappconfig (
    id bigint NOT NULL,
    api_token text NOT NULL,
    phone_number_id character varying(255) NOT NULL,
    business_account_id character varying(255) NOT NULL,
    is_active boolean NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    to_phone_number character varying(50) NOT NULL
);


ALTER TABLE public.tasks_whatsappconfig OWNER TO postgres;

--
-- Name: tasks_whatsappconfig_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tasks_whatsappconfig ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tasks_whatsappconfig_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
1	Master
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
1	1	1
2	1	2
3	1	3
4	1	4
5	1	5
6	1	6
7	1	7
8	1	8
9	1	9
10	1	10
11	1	11
12	1	12
13	1	13
14	1	14
15	1	15
16	1	16
17	1	17
18	1	18
19	1	19
20	1	20
21	1	21
22	1	22
23	1	23
24	1	24
25	1	25
26	1	26
27	1	27
28	1	28
29	1	29
30	1	30
31	1	31
32	1	32
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add team	8	add_team
26	Can change team	8	change_team
27	Can delete team	8	delete_team
28	Can view team	8	view_team
29	Can add task	7	add_task
30	Can change task	7	change_task
31	Can delete task	7	delete_task
32	Can view task	7	view_task
33	Can add Email Configuration	9	add_emailconfig
34	Can change Email Configuration	9	change_emailconfig
35	Can delete Email Configuration	9	delete_emailconfig
36	Can view Email Configuration	9	view_emailconfig
37	Can add n8n Configuration	10	add_n8nconfig
38	Can change n8n Configuration	10	change_n8nconfig
39	Can delete n8n Configuration	10	delete_n8nconfig
40	Can view n8n Configuration	10	view_n8nconfig
41	Can add task sync	11	add_tasksync
42	Can change task sync	11	change_tasksync
43	Can delete task sync	11	delete_tasksync
44	Can view task sync	11	view_tasksync
45	Can add Redis Configuration	13	add_redisconfig
46	Can change Redis Configuration	13	change_redisconfig
47	Can delete Redis Configuration	13	delete_redisconfig
48	Can view Redis Configuration	13	view_redisconfig
49	Can add assignment rule	12	add_assignmentrule
50	Can change assignment rule	12	change_assignmentrule
51	Can delete assignment rule	12	delete_assignmentrule
52	Can view assignment rule	12	view_assignmentrule
53	Can add ClickUp Configuration	14	add_clickupconfig
54	Can change ClickUp Configuration	14	change_clickupconfig
55	Can delete ClickUp Configuration	14	delete_clickupconfig
56	Can view ClickUp Configuration	14	view_clickupconfig
57	Can add Database Configuration	15	add_databaseconfig
58	Can change Database Configuration	15	change_databaseconfig
59	Can delete Database Configuration	15	delete_databaseconfig
60	Can view Database Configuration	15	view_databaseconfig
61	Can add Telegram Configuration	16	add_telegramconfig
62	Can change Telegram Configuration	16	change_telegramconfig
63	Can delete Telegram Configuration	16	delete_telegramconfig
64	Can view Telegram Configuration	16	view_telegramconfig
65	Can add WhatsApp Configuration	17	add_whatsappconfig
66	Can change WhatsApp Configuration	17	change_whatsappconfig
67	Can delete WhatsApp Configuration	17	delete_whatsappconfig
68	Can view WhatsApp Configuration	17	view_whatsappconfig
69	Can add Action Network Configuration	18	add_actionnetworkconfig
70	Can change Action Network Configuration	18	change_actionnetworkconfig
71	Can delete Action Network Configuration	18	delete_actionnetworkconfig
72	Can view Action Network Configuration	18	view_actionnetworkconfig
73	Can add task attachment	19	add_taskattachment
74	Can change task attachment	19	change_taskattachment
75	Can delete task attachment	19	delete_taskattachment
76	Can view task attachment	19	view_taskattachment
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
2	pbkdf2_sha256$1200000$GbkwUXthTGTnEKve7y4Rdv$njMzl6RuGLisEzlMZehknCB0G3qvfyPBcp1dYHx8uGk=	\N	t	harys	harys	rifai	haris.rifai@ops.lgsinarmas.com	t	t	2026-08-02 23:05:34+07
1	pbkdf2_sha256$1200000$dDonatg3MYTT6S3JAiHgUB$6UfdWoP/qrns1TnaiHvC6UhftYNGmsDA/qqvdZrbyqw=	2026-08-04 10:45:25.197855+07	t	admin			admin@localhost	t	t	2026-08-02 22:45:33.237494+07
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
1	2	1
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
1	2	1
2	2	2
3	2	3
4	2	4
5	2	5
6	2	6
7	2	7
8	2	8
9	2	9
10	2	10
11	2	11
12	2	12
13	2	13
14	2	14
15	2	15
16	2	16
17	2	17
18	2	18
19	2	19
20	2	20
21	2	21
22	2	22
23	2	23
24	2	24
25	2	25
26	2	26
27	2	27
28	2	28
29	2	29
30	2	30
31	2	31
32	2	32
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-08-02 23:04:58.637132+07	1	Master	1	[{"added": {}}]	2	1
2	2026-08-02 23:05:36.56297+07	2	harys	1	[{"added": {}}]	4	1
3	2026-08-02 23:05:54.845066+07	2	harys	2	[{"changed": {"fields": ["First name", "Last name", "Email address", "Staff status", "Superuser status", "Groups", "User permissions"]}}]	4	1
4	2026-08-03 13:29:54.30354+07	1	Email Config (Gmail / active)	1	[{"added": {}}]	9	1
5	2026-08-03 13:30:30.881599+07	5	Application -> App Support	2	[]	12	1
6	2026-08-03 13:34:33.118368+07	1	Email Config (Gmail / active)	2	[]	9	1
7	2026-08-03 13:53:45.748709+07	1	ClickUp Config (not set)	1	[{"added": {}}]	14	1
8	2026-08-03 13:53:57.138727+07	1	ClickUp Config (Harys)	2	[{"changed": {"fields": ["Workspace id"]}}]	14	1
9	2026-08-03 13:59:39.40892+07	1	clickup:harys -> SCRQ2 - Assigned	1	[{"added": {}}]	11	1
10	2026-08-03 14:02:06.096632+07	1	Redis Config (redis://localhost:6379/0)	2	[]	13	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	tasks	task
8	tasks	team
9	tasks	emailconfig
10	tasks	n8nconfig
11	tasks	tasksync
12	tasks	assignmentrule
13	tasks	redisconfig
14	tasks	clickupconfig
15	tasks	databaseconfig
16	tasks	telegramconfig
17	tasks	whatsappconfig
18	tasks	actionnetworkconfig
19	tasks	taskattachment
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-08-02 22:45:17.699478+07
2	auth	0001_initial	2026-08-02 22:45:17.908438+07
3	admin	0001_initial	2026-08-02 22:45:17.979517+07
4	admin	0002_logentry_remove_auto_add	2026-08-02 22:45:18.007425+07
5	admin	0003_logentry_add_action_flag_choices	2026-08-02 22:45:18.031062+07
6	contenttypes	0002_remove_content_type_name	2026-08-02 22:45:18.08952+07
7	auth	0002_alter_permission_name_max_length	2026-08-02 22:45:18.133689+07
8	auth	0003_alter_user_email_max_length	2026-08-02 22:45:18.1644+07
9	auth	0004_alter_user_username_opts	2026-08-02 22:45:18.194095+07
10	auth	0005_alter_user_last_login_null	2026-08-02 22:45:18.215681+07
11	auth	0006_require_contenttypes_0002	2026-08-02 22:45:18.21768+07
12	auth	0007_alter_validators_add_error_messages	2026-08-02 22:45:18.234779+07
13	auth	0008_alter_user_username_max_length	2026-08-02 22:45:18.266465+07
14	auth	0009_alter_user_last_name_max_length	2026-08-02 22:45:18.29978+07
15	auth	0010_alter_group_name_max_length	2026-08-02 22:45:18.336619+07
16	auth	0011_update_proxy_permissions	2026-08-02 22:45:18.357722+07
17	auth	0012_alter_user_first_name_max_length	2026-08-02 22:45:18.38424+07
18	sessions	0001_initial	2026-08-02 22:45:18.41955+07
19	tasks	0001_initial	2026-08-02 22:45:18.50095+07
20	tasks	0002_emailconfig	2026-08-03 11:38:52.99963+07
21	tasks	0003_n8nconfig	2026-08-03 12:21:11.514898+07
22	tasks	0004_task_external_id_task_source_tasksync	2026-08-03 12:23:41.675489+07
23	tasks	0005_alter_n8nconfig_api_key	2026-08-03 12:30:10.289422+07
24	tasks	0006_redisconfig_assignmentrule	2026-08-03 12:38:03.306034+07
25	tasks	0007_populate_default_rules	2026-08-03 13:29:46.275968+07
26	tasks	0008_clickupconfig	2026-08-03 13:42:45.022942+07
27	tasks	0009_databaseconfig	2026-08-03 15:54:36.823419+07
28	tasks	0010_telegramconfig_whatsappconfig	2026-08-03 16:51:00.434343+07
29	tasks	0011_actionnetworkconfig	2026-08-03 17:32:28.82234+07
30	tasks	0012_taskattachment	2026-08-03 23:35:01.496732+07
31	tasks	0013_add_whatsapp_to_phone_number	2026-08-04 08:30:45.918976+07
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
lcyf0spb3nploov33980l8qfzmnhmat2	.eJxVjMsOwiAQRf-FtSG8B1y69xvIMIBUDU1KuzL-uzbpQrf3nHNfLOK2triNssQpszOT7PS7JaRH6TvId-y3mdPc12VKfFf4QQe_zrk8L4f7d9BwtG-tybrilTKhIhjyIQifgiJALQG0kk4bQza7KoUPVVpX0Qok7zFYAmDvD7iNNtA:1wqYgA:bT-yJM8NUi127reKF1XToqLZhsVWLGGGj53NNwNW4sM	2026-08-16 23:04:46.560045+07
5rzo8soof299knu04nuwu5fnxng6kgg2	.eJxVjMsOwiAQRf-FtSG8B1y69xvIMIBUDU1KuzL-uzbpQrf3nHNfLOK2triNssQpszOT7PS7JaRH6TvId-y3mdPc12VKfFf4QQe_zrk8L4f7d9BwtG-tybrilTKhIhjyIQifgiJALQG0kk4bQza7KoUPVVpX0Qok7zFYAmDvD7iNNtA:1wqtkS:cZDkE1r_96PtASlBrsLuK_Lqk1_onPy9oRgSthBS2PA	2026-08-17 21:34:36.929607+07
35pvxmq5bswgh48x0z7v1gvnpv6ygppo	.eJxVjMsOwiAQRf-FtSG8B1y69xvIMIBUDU1KuzL-uzbpQrf3nHNfLOK2triNssQpszOT7PS7JaRH6TvId-y3mdPc12VKfFf4QQe_zrk8L4f7d9BwtG-tybrilTKhIhjyIQifgiJALQG0kk4bQza7KoUPVVpX0Qok7zFYAmDvD7iNNtA:1wr65l:kFV6Tv25AF1ZS-lE0eWnNlkbeyb-iDNlJwjlkovQ-5o	2026-08-18 10:45:25.200968+07
\.


--
-- Data for Name: tasks_actionnetworkconfig; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tasks_actionnetworkconfig (id, api_key, webhook_url, webhook_secret, is_active, updated_at) FROM stdin;
1				t	2026-08-03 17:35:00.539353+07
\.


--
-- Data for Name: tasks_assignmentrule; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tasks_assignmentrule (id, keyword, is_active, team_id) FROM stdin;
1	SAP	t	1
2	Database	t	2
3	VPN	t	3
4	Laptop	t	4
5	Application	f	5
\.


--
-- Data for Name: tasks_clickupconfig; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tasks_clickupconfig (id, api_token, workspace_id, is_active, updated_at) FROM stdin;
1	pk_222137082_Z27FN3G01P0DESM24GC8JDX2SQMQBR59	Harys	t	2026-08-03 21:38:39.225028+07
\.


--
-- Data for Name: tasks_databaseconfig; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tasks_databaseconfig (id, engine, name, "user", password, host, port, is_active, updated_at) FROM stdin;
1	postgresql	taskdb	postgres	Password09!	localhost	5008	t	2026-08-03 21:38:42.830848+07
\.


--
-- Data for Name: tasks_emailconfig; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tasks_emailconfig (id, provider, host, port, username, password, use_tls, use_ssl, from_email, from_name, is_active, updated_at) FROM stdin;
1	gmail	smtp.gmail.com	587	apps.bit.inv@gmail.com	Dikpora31!	t	f	apps.bit.inv@gmail.com	Task Management	t	2026-08-03 13:34:33.115413+07
\.


--
-- Data for Name: tasks_n8nconfig; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tasks_n8nconfig (id, base_url, api_key, is_active, updated_at) FROM stdin;
1	http://localhost:5678	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZGVhZDhkZS03NDY1LTQxY2UtOTIyYS1mZDdjMWQ2YjI1NWQiLCJpc3MiOiJuOG4iLCJhdWQiOiJwdWJsaWMtYXBpIiwianRpIjoiNjM1NDc4ZDItOGJkNi00YmUxLWI5YmEtMmFiODk1MWUyODRiIiwiaWF0IjoxNzg1NzM0OTEwfQ.4uStSp8chw2G5d8vcE1wQhdEtmogbkxRMi1oB5lrhxI	t	2026-08-03 21:38:44.35053+07
\.


--
-- Data for Name: tasks_redisconfig; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tasks_redisconfig (id, url, is_active, updated_at) FROM stdin;
1	redis://localhost:6379/0	t	2026-08-04 09:09:26.901472+07
\.


--
-- Data for Name: tasks_task; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tasks_task (id, job_id, email_from, email_subject, task_type, task_detail, priority, note, status, created_at, updated_at, closed_at, assign_to_id, external_id, source) FROM stdin;
8	SCRQ3	Dev.CRQ@taskmant.co.id	Action Drop DB	Update database openapi	Update Version database	High	On Progress	Pending User	2026-08-03 23:05:29.268476+07	2026-08-03 23:39:03.104342+07	\N	3		
3	SCRQ5	Dev.CRQ@taskmant.co.id	Task from external	Database	Update Version database	Medium	On Progress	Open	2026-08-03 14:38:22.365678+07	2026-08-04 09:12:21.397599+07	\N	\N	ext-1	n8n
9	SCRQ4	Dev.CRQ@taskmant.co.id	Maintenace Database SVR	Database	Update Version database	High	On Progress	Open	2026-08-04 08:58:32.132432+07	2026-08-04 10:52:07.413381+07	\N	2		
4	SCRQ6	Dev.CRQ@taskmant.co.id	Task from external	Database	Update Version database	High	On Progress	Open	2026-07-29 17:34:58+07	2026-08-03 23:40:36.371406+07	2026-08-03 23:22:16.763585+07	3	test-1	test
5	SCRQ7	Dev.CRQ@taskmant.co.id	Action Task	Action Network	Update Version database	Medium	On Progress	In Progress	2026-07-30 17:36:00+07	2026-08-03 17:36:00.437116+07	2026-08-03 23:30:57.561592+07	3	AN-1	action_network
2	SCRQ2	Dev.CRQ@taskmant.co.id	Maintenace Database SVR	Update database openapi	git remote add origin https://github.com/harys-rifai/TaskMgmt-synchAPPS.git\r\ngit branch -M main\r\ngit push -u origin main	High	On Progress	Closed	2026-07-29 13:44:21+07	2026-08-04 10:53:28.685074+07	2026-08-03 23:27:14.184644+07	2		
1	SCRQ1	Dev.CRQ@taskmant.co.id	Maintenace Database SVR	Update database openapi	Update database openapi	High	On Progress	Assigned	2026-08-03 11:38:14.098153+07	2026-08-03 23:34:23.169947+07	\N	\N		
\.


--
-- Data for Name: tasks_taskattachment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tasks_taskattachment (id, file, filename, content_type, uploaded_at, task_id, uploaded_by_id) FROM stdin;
1	task_attachments/2026/08/03/absen-white.png	absen-white.png	image/png	2026-08-03 23:40:40.125131+07	4	1
\.


--
-- Data for Name: tasks_tasksync; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tasks_tasksync (id, source, external_id, raw, synced_at, task_id) FROM stdin;
1	clickup	harys	{}	2026-08-03 13:59:39.400912+07	2
3	test	test-1	{}	2026-08-03 17:34:58.488401+07	4
4	action_network	AN-1	{"id": "AN-1", "title": "Action Task", "description": "Action desc"}	2026-08-03 17:36:00.440114+07	5
2	clickup	ext-1	{}	2026-08-03 14:38:22.397867+07	3
5	n8n	ext-1	{}	2026-08-04 09:12:21.407635+07	3
\.


--
-- Data for Name: tasks_team; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tasks_team (id, name, email, is_active) FROM stdin;
1	SAP Team		t
2	DBA Team		t
3	Network Team		t
4	IT Support		t
5	App Support		t
\.


--
-- Data for Name: tasks_telegramconfig; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tasks_telegramconfig (id, bot_token, chat_id, is_active, updated_at) FROM stdin;
1	8638698502:AAHBpy7o0w9EaaMheyP6jkDaENqJcFjuELU	@JourneyDevBot	t	2026-08-04 09:09:48.146385+07
\.


--
-- Data for Name: tasks_whatsappconfig; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tasks_whatsappconfig (id, api_token, phone_number_id, business_account_id, is_active, updated_at, to_phone_number) FROM stdin;
1	admin123		admin	t	2026-08-03 21:38:37.272676+07	
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, true);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 32, true);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 76, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, true);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 2, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 32, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 10, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 19, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 31, true);


--
-- Name: tasks_actionnetworkconfig_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tasks_actionnetworkconfig_id_seq', 1, false);


--
-- Name: tasks_assignmentrule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tasks_assignmentrule_id_seq', 5, true);


--
-- Name: tasks_clickupconfig_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tasks_clickupconfig_id_seq', 1, false);


--
-- Name: tasks_databaseconfig_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tasks_databaseconfig_id_seq', 1, false);


--
-- Name: tasks_emailconfig_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tasks_emailconfig_id_seq', 1, false);


--
-- Name: tasks_n8nconfig_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tasks_n8nconfig_id_seq', 1, false);


--
-- Name: tasks_redisconfig_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tasks_redisconfig_id_seq', 1, false);


--
-- Name: tasks_task_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tasks_task_id_seq', 10, true);


--
-- Name: tasks_taskattachment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tasks_taskattachment_id_seq', 1, true);


--
-- Name: tasks_tasksync_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tasks_tasksync_id_seq', 6, true);


--
-- Name: tasks_team_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tasks_team_id_seq', 5, true);


--
-- Name: tasks_telegramconfig_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tasks_telegramconfig_id_seq', 1, false);


--
-- Name: tasks_whatsappconfig_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tasks_whatsappconfig_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: tasks_actionnetworkconfig tasks_actionnetworkconfig_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_actionnetworkconfig
    ADD CONSTRAINT tasks_actionnetworkconfig_pkey PRIMARY KEY (id);


--
-- Name: tasks_assignmentrule tasks_assignmentrule_keyword_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_assignmentrule
    ADD CONSTRAINT tasks_assignmentrule_keyword_key UNIQUE (keyword);


--
-- Name: tasks_assignmentrule tasks_assignmentrule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_assignmentrule
    ADD CONSTRAINT tasks_assignmentrule_pkey PRIMARY KEY (id);


--
-- Name: tasks_clickupconfig tasks_clickupconfig_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_clickupconfig
    ADD CONSTRAINT tasks_clickupconfig_pkey PRIMARY KEY (id);


--
-- Name: tasks_databaseconfig tasks_databaseconfig_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_databaseconfig
    ADD CONSTRAINT tasks_databaseconfig_pkey PRIMARY KEY (id);


--
-- Name: tasks_emailconfig tasks_emailconfig_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_emailconfig
    ADD CONSTRAINT tasks_emailconfig_pkey PRIMARY KEY (id);


--
-- Name: tasks_n8nconfig tasks_n8nconfig_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_n8nconfig
    ADD CONSTRAINT tasks_n8nconfig_pkey PRIMARY KEY (id);


--
-- Name: tasks_redisconfig tasks_redisconfig_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_redisconfig
    ADD CONSTRAINT tasks_redisconfig_pkey PRIMARY KEY (id);


--
-- Name: tasks_task tasks_task_job_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_task
    ADD CONSTRAINT tasks_task_job_id_key UNIQUE (job_id);


--
-- Name: tasks_task tasks_task_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_task
    ADD CONSTRAINT tasks_task_pkey PRIMARY KEY (id);


--
-- Name: tasks_taskattachment tasks_taskattachment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_taskattachment
    ADD CONSTRAINT tasks_taskattachment_pkey PRIMARY KEY (id);


--
-- Name: tasks_tasksync tasks_tasksync_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_tasksync
    ADD CONSTRAINT tasks_tasksync_pkey PRIMARY KEY (id);


--
-- Name: tasks_tasksync tasks_tasksync_source_external_id_47de86a2_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_tasksync
    ADD CONSTRAINT tasks_tasksync_source_external_id_47de86a2_uniq UNIQUE (source, external_id);


--
-- Name: tasks_team tasks_team_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_team
    ADD CONSTRAINT tasks_team_pkey PRIMARY KEY (id);


--
-- Name: tasks_telegramconfig tasks_telegramconfig_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_telegramconfig
    ADD CONSTRAINT tasks_telegramconfig_pkey PRIMARY KEY (id);


--
-- Name: tasks_whatsappconfig tasks_whatsappconfig_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_whatsappconfig
    ADD CONSTRAINT tasks_whatsappconfig_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: tasks_assignmentrule_keyword_f281f8c0_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tasks_assignmentrule_keyword_f281f8c0_like ON public.tasks_assignmentrule USING btree (keyword varchar_pattern_ops);


--
-- Name: tasks_assignmentrule_team_id_4c4e3244; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tasks_assignmentrule_team_id_4c4e3244 ON public.tasks_assignmentrule USING btree (team_id);


--
-- Name: tasks_task_assign_to_id_b1eb610b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tasks_task_assign_to_id_b1eb610b ON public.tasks_task USING btree (assign_to_id);


--
-- Name: tasks_task_external_id_e23a3bf4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tasks_task_external_id_e23a3bf4 ON public.tasks_task USING btree (external_id);


--
-- Name: tasks_task_external_id_e23a3bf4_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tasks_task_external_id_e23a3bf4_like ON public.tasks_task USING btree (external_id varchar_pattern_ops);


--
-- Name: tasks_task_job_id_1feb2a15_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tasks_task_job_id_1feb2a15_like ON public.tasks_task USING btree (job_id varchar_pattern_ops);


--
-- Name: tasks_task_source_317be3ef; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tasks_task_source_317be3ef ON public.tasks_task USING btree (source);


--
-- Name: tasks_task_source_317be3ef_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tasks_task_source_317be3ef_like ON public.tasks_task USING btree (source varchar_pattern_ops);


--
-- Name: tasks_taskattachment_task_id_6d63b288; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tasks_taskattachment_task_id_6d63b288 ON public.tasks_taskattachment USING btree (task_id);


--
-- Name: tasks_taskattachment_uploaded_by_id_94a932b7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tasks_taskattachment_uploaded_by_id_94a932b7 ON public.tasks_taskattachment USING btree (uploaded_by_id);


--
-- Name: tasks_tasksync_external_id_cdc5e8ba; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tasks_tasksync_external_id_cdc5e8ba ON public.tasks_tasksync USING btree (external_id);


--
-- Name: tasks_tasksync_external_id_cdc5e8ba_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tasks_tasksync_external_id_cdc5e8ba_like ON public.tasks_tasksync USING btree (external_id varchar_pattern_ops);


--
-- Name: tasks_tasksync_task_id_0b694d94; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tasks_tasksync_task_id_0b694d94 ON public.tasks_tasksync USING btree (task_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tasks_assignmentrule tasks_assignmentrule_team_id_4c4e3244_fk_tasks_team_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_assignmentrule
    ADD CONSTRAINT tasks_assignmentrule_team_id_4c4e3244_fk_tasks_team_id FOREIGN KEY (team_id) REFERENCES public.tasks_team(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tasks_task tasks_task_assign_to_id_b1eb610b_fk_tasks_team_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_task
    ADD CONSTRAINT tasks_task_assign_to_id_b1eb610b_fk_tasks_team_id FOREIGN KEY (assign_to_id) REFERENCES public.tasks_team(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tasks_taskattachment tasks_taskattachment_task_id_6d63b288_fk_tasks_task_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_taskattachment
    ADD CONSTRAINT tasks_taskattachment_task_id_6d63b288_fk_tasks_task_id FOREIGN KEY (task_id) REFERENCES public.tasks_task(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tasks_taskattachment tasks_taskattachment_uploaded_by_id_94a932b7_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_taskattachment
    ADD CONSTRAINT tasks_taskattachment_uploaded_by_id_94a932b7_fk_auth_user_id FOREIGN KEY (uploaded_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tasks_tasksync tasks_tasksync_task_id_0b694d94_fk_tasks_task_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_tasksync
    ADD CONSTRAINT tasks_tasksync_task_id_0b694d94_fk_tasks_task_id FOREIGN KEY (task_id) REFERENCES public.tasks_task(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict hyR4KezQV0VrSlIls5NQfHoWqzRbeUdvyhpDxKsk7gEn7WopyM4MCbKlEBJuGmZ

