# Generated by Django 6.0.7 on 2026-08-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook / Office 365'), ('yahoo', 'Yahoo Mail'), ('sendgrid', 'SendGrid'), ('mailgun', 'Mailgun'), ('custom', 'Custom SMTP')], default='gmail', max_length=20)),
                ('host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('username', models.CharField(blank=True, help_text='SMTP username / email address', max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('from_email', models.EmailField(blank=True, help_text='Displayed sender address (defaults to username)', max_length=254)),
                ('from_name', models.CharField(blank=True, default='Task Management', help_text='Displayed sender name', max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Enable outbound email')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'db_table': 'tasks_emailconfig',
            },
        ),
    ]
