# Generated by Django 6.0.7 on 2026-08-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_emailconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='N8nConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(default='http://localhost:5678', help_text='n8n instance base URL', max_length=255)),
                ('api_key', models.CharField(blank=True, help_text='n8n API key (optional)', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Enable n8n integration')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'n8n Configuration',
                'db_table': 'tasks_n8nconfig',
            },
        ),
    ]
