# Generated by Django 6.0.7 on 2026-08-03 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_n8nconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='source',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='TaskSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('email', 'Email'), ('teams', 'Microsoft Teams'), ('clickup', 'ClickUp'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram')], max_length=20)),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syncs', to='tasks.task')),
            ],
            options={
                'db_table': 'tasks_tasksync',
                'ordering': ['-synced_at'],
                'unique_together': {('source', 'external_id')},
            },
        ),
    ]
