# Generated by Django 6.0.7 on 2026-08-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_external_id_task_source_tasksync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='n8nconfig',
            name='api_key',
            field=models.TextField(blank=True, help_text='n8n API key (optional)'),
        ),
    ]
