# Generated by Django 6.0.7 on 2026-08-03 06:29

from django.db import migrations


def create_defaults(apps, schema_editor):
    Team = apps.get_model('tasks', 'Team')
    AssignmentRule = apps.get_model('tasks', 'AssignmentRule')

    teams = {
        'SAP Team':       Team.objects.get_or_create(name='SAP Team', defaults={'email': '', 'is_active': True})[0],
        'DBA Team':       Team.objects.get_or_create(name='DBA Team', defaults={'email': '', 'is_active': True})[0],
        'Network Team':   Team.objects.get_or_create(name='Network Team', defaults={'email': '', 'is_active': True})[0],
        'IT Support':     Team.objects.get_or_create(name='IT Support', defaults={'email': '', 'is_active': True})[0],
        'App Support':    Team.objects.get_or_create(name='App Support', defaults={'email': '', 'is_active': True})[0],
    }

    rules = [
        ('SAP',       teams['SAP Team']),
        ('Database',  teams['DBA Team']),
        ('VPN',       teams['Network Team']),
        ('Laptop',    teams['IT Support']),
        ('Application', teams['App Support']),
    ]

    for keyword, team in rules:
        AssignmentRule.objects.get_or_create(keyword=keyword, defaults={'team': team, 'is_active': True})


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_redisconfig_assignmentrule'),
    ]

    operations = [
        migrations.RunPython(create_defaults, migrations.RunPython.noop),
    ]
