# Generated by Django 6.0.7 on 2026-08-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_populate_default_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickUpConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_token', models.TextField(blank=True, help_text='ClickUp API token (Personal API Key)')),
                ('workspace_id', models.CharField(blank=True, help_text='ClickUp Workspace ID', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Enable ClickUp integration')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ClickUp Configuration',
                'db_table': 'tasks_clickupconfig',
            },
        ),
    ]
