# Generated by Django 6.0.7 on 2026-08-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_clickupconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('sqlite3', 'SQLite3')], default='postgresql', max_length=20)),
                ('name', models.CharField(default='taskdb', max_length=255)),
                ('user', models.CharField(default='postgres', max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('host', models.CharField(default='localhost', max_length=255)),
                ('port', models.CharField(default='5008', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Database Configuration',
                'db_table': 'tasks_databaseconfig',
            },
        ),
    ]
