# Generated by Django 6.0.7 on 2026-08-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_databaseconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.TextField(blank=True, help_text='Telegram Bot Token from @BotFather')),
                ('chat_id', models.CharField(blank=True, help_text='Telegram Chat/Group ID', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Enable Telegram integration')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Configuration',
                'db_table': 'tasks_telegramconfig',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_token', models.TextField(blank=True, help_text='WhatsApp Business API token')),
                ('phone_number_id', models.CharField(blank=True, help_text='WhatsApp Phone Number ID', max_length=255)),
                ('business_account_id', models.CharField(blank=True, help_text='WhatsApp Business Account ID', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Enable WhatsApp integration')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Configuration',
                'db_table': 'tasks_whatsappconfig',
            },
        ),
    ]
