# Generated by Django 6.0.7 on 2026-08-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_telegramconfig_whatsappconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionNetworkConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.TextField(blank=True, help_text='Action Network API Key')),
                ('webhook_url', models.CharField(blank=True, help_text='Action Network webhook callback URL', max_length=255)),
                ('webhook_secret', models.CharField(blank=True, help_text='Webhook verification secret', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Enable Action Network integration')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Action Network Configuration',
                'db_table': 'tasks_actionnetworkconfig',
            },
        ),
    ]
