# Generated by Django 6.0.7 on 2026-08-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_taskattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconfig',
            name='to_phone_number',
            field=models.CharField(blank=True, help_text='Recipient phone number in E.164 format, e.g. +628123456789', max_length=50),
        ),
        migrations.AlterField(
            model_name='whatsappconfig',
            name='phone_number_id',
            field=models.CharField(blank=True, help_text='WhatsApp Phone Number ID (sender)', max_length=255),
        ),
    ]
