# Generated by Django 6.0.7 on 2026-08-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_add_whatsapp_to_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='closed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='email_from',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(db_index=True, default='Open', max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', '-created_at'], name='task_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'created_at'], name='task_status_created_asc_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'closed_at'], name='task_status_closed_idx'),
        ),
    ]
